### ISSUE TITLE
启动不成功

### ISSUE THREAD

**Issue by biousco** [leinue/vue-feeds#1]
npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\biousco\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--userconfig=C:\\Users\\biousco\\.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--cache=C:\\Users\\biousco\\.cnpm',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   '--node-gyp=C:\\Users\\biousco\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\pangyp\\bin\\node-gyp.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.7.6
3 info using node@v4.1.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev poimoe_poi@0.0.1
6 info dev poimoe_poi@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info poimoe_poi@0.0.1 Failed to exec dev script
9 verbose stack Error: poimoe_poi@0.0.1 dev: `webpack-dev-server --inline --hot --quiet`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\biousco\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\biousco\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid poimoe_poi@0.0.1
11 verbose cwd E:\Git\sina\vue-feeds
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\biousco\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\biousco\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\biousco\\.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=C:\\Users\\biousco\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\pangyp\\bin\\node-gyp.js" "run" "dev"
14 error node v4.1.1
15 error npm  v2.7.6
16 error code ELIFECYCLE
17 error poimoe_poi@0.0.1 dev: `webpack-dev-server --inline --hot --quiet`
17 error Exit status 1
18 error Failed at the poimoe_poi@0.0.1 dev script 'webpack-dev-server --inline --hot --quiet'.
18 error This is most likely a problem with the poimoe_poi package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --inline --hot --quiet
18 error You can get their info via:
18 error     npm owner ls poimoe_poi
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

你好！运行`npm run dev`时，出现到`content is served from E:\Git\sina\vue-feeds`后就开始报错。请问是什么原因？需要的依赖都安装好了。谢谢。

**Comment by leinue** [comment]
我用mac osx开发的，估计和windows不兼容，我也暂时无法解决，抱歉

**Comment by biousco** [comment]
用Linux也是同样的问题：

```
[root@localhost vue-feeds]# npm run dev

> poimoe_poi@0.0.1 dev /root/vue-seeds/vue-feeds
> webpack-dev-server --inline --hot --quiet

http://localhost:8080/
webpack result is served from /
content is served from /root/vue-seeds/vue-feeds
/root/vue-seeds/vue-feeds/node_modules/webpack-core/lib/NormalModuleMixin.js:163
            if(isError) throw e;
                        ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/root/vue-seeds/vue-feeds/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:100:32)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/root/vue-seeds/vue-feeds/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:159:16)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/root/vue-seeds/vue-feeds/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:84:26)
    at SourceMapSource.node (/root/vue-seeds/vue-feeds/node_modules/webpack-core/lib/SourceMapSource.js:41:20)
    at ReplaceSource.node (/root/vue-seeds/vue-feeds/node_modules/webpack-core/lib/ReplaceSource.js:64:29)
    at CachedSource.node (/root/vue-seeds/vue-feeds/node_modules/webpack-core/lib/CachedSource.js:41:22)
    at PrefixSource.node (/root/vue-seeds/vue-feeds/node_modules/webpack-core/lib/PrefixSource.js:27:26)
    at /root/vue-seeds/vue-feeds/node_modules/webpack-core/lib/ConcatSource.js:38:49
    at Array.map (native)

npm ERR! Linux 2.6.32-042stab111.11
npm ERR! argv "/root/.nvm/versions/node/v5.2.0/bin/node" "/root/.nvm/versions/node/v5.2.0/bin/npm" "run" "dev"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! poimoe_poi@0.0.1 dev: `webpack-dev-server --inline --hot --quiet`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poimoe_poi@0.0.1 dev script 'webpack-dev-server --inline --hot --quiet'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poimoe_poi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --quiet
npm ERR! You can get their info via:
npm ERR!     npm owner ls poimoe_poi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/vue-seeds/vue-feeds/npm-debug.log
```

```
Linux version 2.6.32-042stab111.11 (root@kbuild-rh6-x64.eng.sw.ru) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Tue Sep 1 18:19:12 MSK 2015
```

**Comment by leinue** [comment]
1、升级npm
2、http://www.jianshu.com/p/941bfaf13be1 来这里了解一下webpack-dev-server

**Comment by leinue** [comment]
或者直接输入webpack看能不能用

**Comment by leinue** [comment]
webpack-dev-server是作为开发模式热更新用的，可以先尝试webpack命令编译，然后打开index.html即可。如果成功了再尝试配置下webpack-dev-server

**Comment by lixsyulin** [comment]
webpack可以了

**Comment by leinue** [comment]
vim package.json
找到babel-runtime
修改后面的版本号为^5.8.0
然后执行npm install
再执行 npm run dev即可
